### PR TITLE
update content of the hackathon page

### PR DESCRIPTION
**Pull request by Remi-Gau**
- to better match content of the hackathon github README

### CODE REVIEW

**Comment by cmaumet** [comment]
@Remi-Gau: I've added a couple more info from our save-the-date email, let me know what you think :D

**Comment by Remi-Gau** [comment]
Looks good. Shall we merge?

**Comment by cmaumet** [comment]
Yes! Please :D

**Comment by Remi-Gau** [comment]
Done. :-)

**Pull request merged**
